import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Search,ShoppingCart,UserRound,MapPin,ChevronRight,Plus,Minus,Menu,X,Heart,ShieldCheck,LogOut,Upload,Clock,Truck,FileText,Star,ArrowRight,Stethoscope,Store,PackageCheck}from"lucide-react";import{supabase}from"./lib/supabase";import{googleLogin,sendPhoneOtp,verifyPhoneOtp,signOut,ensureProfile}from"./lib/auth";import"./styles.css";import"./portal.css";import Portal from"./portal";
const fallback=[{id:1,n:"Dolo 650",b:"Micro Labs",p:30,mrp:35,c:"Pain Relief",salt:"Paracetamol 650mg",rx:false,img:"💊"},{id:2,n:"Limcee Vitamin C 500mg",b:"Abbott",p:22,mrp:25,c:"Vitamins",salt:"Vitamin C",rx:false,img:"🍊"},{id:3,n:"Honitus Sugar Free 100ml",b:"Dabur",p:145,mrp:165,c:"Cough & Cold",salt:"Herbal formulation",rx:false,img:"🧴"},{id:4,n:"Cetaphil Gentle Skin Cleanser",b:"Galderma",p:399,mrp:450,c:"Skin Care",salt:"Gentle cleanser",rx:false,img:"🧼"},{id:5,n:"Pedigree Adult Dog Food",b:"Pedigree",p:210,mrp:240,c:"Pet Care",salt:"Adult nutrition",rx:false,img:"🐕"},{id:6,n:"First Aid Kit",b:"Wellcare",p:299,mrp:349,c:"First Aid",salt:"Essential first aid",rx:false,img:"🩹"},{id:7,n:"Shelcal 500",b:"Torrent",p:118,mrp:135,c:"Bone & Joint",salt:"Calcium + Vitamin D3",rx:false,img:"💊"},{id:8,n:"Azithromycin 500mg",b:"Cipla",p:92,mrp:105,c:"Anti Infective",salt:"Azithromycin",rx:true,img:"💊"}];
const cats=[["Medicines","💊"],["Pain Relief","🩹"],["Cough & Cold","🌿"],["Vitamins","🍊"],["Diabetes","🩺"],["Heart Care","❤️"],["Skin Care","🧴"],["Baby Care","🍼"],["Pet Care","🐾"],["First Aid","🩺"]];
function App(){
 const[products,setProducts]=useState(fallback),[branches,setBranches]=useState([]),[branch,setBranch]=useState(""),[cart,setCart]=useState([]),[login,setLogin]=useState(false),[checkout,setCheckout]=useState(false),[menu,setMenu]=useState(false),[search,setSearch]=useState(""),[session,setSession]=useState(null),[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[otpSent,setOtpSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[cat,setCat]=useState(""),[rx,setRx]=useState(false),[addresses,setAddresses]=useState([]),[address,setAddress]=useState(""),[method,setMethod]=useState("delivery"),[payment,setPayment]=useState("cash"),[message,setMessage]=useState(""),[rxFile,setRxFile]=useState(null);
 useEffect(()=>{loadBranches();supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session?.user){ensureProfile(data.session.user);loadCart(data.session.user.id);loadAddresses(data.session.user.id)}});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s?.user){ensureProfile(s.user);loadCart(s.user.id);loadAddresses(s.user.id)}});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(branch){loadProducts(branch);if(session?.user)loadCart(session.user.id)}},[branch]);
 async function loadBranches(){const{data}=await supabase.from("branches").select("id,name,code,city,state").eq("active",true).order("name");setBranches(data||[]);if(data?.[0])setBranch(data[0].id)}
 async function loadProducts(id){const{data}=await supabase.from("branch_products").select("product_id,price,stock,active,products:product_id(id,name,brand,category,description,mrp,images,prescription_required)").eq("branch_id",id).eq("active",true);if(data?.length)setProducts(data.filter(x=>x.products).map(x=>({...x.products,id:x.product_id,n:x.products.name,b:x.products.brand,p:Number(x.price),mrp:Number(x.products.mrp),c:x.products.category,salt:x.products.description||"",rx:!!x.products.prescription_required,img:"💊",stock:x.stock})))}
 async function loadCart(uid){const{data}=await supabase.from("cart_items").select("product_id,quantity,products:product_id(id,name,brand,mrp,category,description,prescription_required),branch_products:product_id(price,stock,branch_id)").eq("user_id",uid);if(data)setCart(data.filter(x=>x.products).map(x=>{const bp=(x.branch_products||[]).find(v=>v.branch_id===branch);return {...x.products,id:x.product_id,n:x.products.name,b:x.products.brand,mrp:x.products.mrp,p:Number(bp?.price??x.products.mrp),stock:bp?.stock??0,c:x.products.category,salt:x.products.description||"",rx:!!x.products.prescription_required,qty:x.quantity,img:"💊"}}))}
 async function loadAddresses(uid){const{data}=await supabase.from("addresses").select("*").eq("user_id",uid).order("is_default",{ascending:false});setAddresses(data||[]);if(data?.[0])setAddress(data[0].id)}
 async function add(p){if(!session){setLogin(true);return}const q=(cart.find(x=>x.id===p.id)?.qty||0)+1;const{error}=await supabase.from("cart_items").upsert({user_id:session.user.id,product_id:p.id,quantity:q},{onConflict:"user_id,product_id"});if(error)setError(error.message);else setCart(c=>{const old=c.find(x=>x.id===p.id);return old?c.map(x=>x.id===p.id?{...x,qty:q}:x):[...c,{...p,qty:1}]})}
 async function change(p,d){const old=cart.find(x=>x.id===p.id);if(!old)return;const q=old.qty+d;if(q<=0){await supabase.from("cart_items").delete().eq("user_id",session.user.id).eq("product_id",p.id);setCart(c=>c.filter(x=>x.id!==p.id))}else{await supabase.from("cart_items").update({quantity:q}).eq("user_id",session.user.id).eq("product_id",p.id);setCart(c=>c.map(x=>x.id===p.id?{...x,qty:q}:x))}}
 async function google(){setBusy(true);setError("");const{error}=await googleLogin();if(error)setError(error.message);setBusy(false)}
 async function send(){setBusy(true);const n=phone.trim().startsWith("+")?phone.trim():"+91"+phone.replace(/\D/g,"");const{error}=await sendPhoneOtp(n);if(error)setError(error.message);else{setPhone(n);setOtpSent(true)}setBusy(false)}
 async function verify(){setBusy(true);const{data,error}=await verifyPhoneOtp(phone,otp.trim());if(error)setError(error.message);else{setSession(data.session);setLogin(false);setOtpSent(false);await loadCart(data.session.user.id);await loadAddresses(data.session.user.id)}setBusy(false)}
 async function uploadPrescription(){
  if(!session){setLogin(true);return}
  if(!rxFile)return setError("Choose a prescription file first.");
  if(rxFile.size>5*1024*1024)return setError("Prescription must be 5 MB or smaller.");
  setBusy(true);setError("");
  const ext=(rxFile.name.split(".").pop()||"bin").toLowerCase();
  const path=session.user.id+"/"+Date.now()+"."+ext;
  const up=await supabase.storage.from("prescriptions").upload(path,rxFile,{contentType:rxFile.type,upsert:false});
  if(up.error){setError(up.error.message);setBusy(false);return}
  const ins=await supabase.from("prescriptions").insert({user_id:session.user.id,storage_path:path,status:"pending"});
  if(ins.error){
    await supabase.storage.from("prescriptions").remove([path]);
    setError(ins.error.message);
  }else{
    setMessage("Prescription uploaded · pharmacy review pending");
    setRx(false);setRxFile(null);
  }
  setBusy(false)
}
 async function order(){if(!session){setLogin(true);return}if(!branch)return setError("Select a store first.");if(method==="delivery"&&!address)return setError("Select a delivery address.");setBusy(true);setError("");const{data,error}=await supabase.rpc("create_customer_order",{p_branch_id:branch,p_fulfillment_method:method,p_address_id:method==="delivery"?address:null,p_payment_method:payment});if(error)setError(error.message);else{setCheckout(false);setCart([]);setMessage("Order placed successfully · #"+String(data).slice(0,8));}setBusy(false)}
 async function logout(){await signOut();setLogin(false);setCart([])}
 const shown=useMemo(()=>products.filter(p=>(!cat||p.c===cat)&&(!search||((p.n+" "+p.b+" "+p.salt).toLowerCase().includes(search.toLowerCase())))),[search,cat,products]);
 const count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+x.p*x.qty,0);
 return <>{/* header */}<header><div className="top"><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="logo"><span>W</span><b>Wellcare</b><small>MEDICOSE</small></div><button className="location" onClick={()=>setCheckout(true)}><MapPin size={18}/><div><small>Store</small><strong>{branches.find(x=>x.id===branch)?.name||"Select store"}</strong></div></button><div className="searchWrap"><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search medicines, brands, salt or health products"/></div></div><button className="account" onClick={()=>setLogin(true)}><UserRound/><span>{session?.user?.user_metadata?.name||"Account"}</span></button><button className="cart" onClick={()=>setCheckout(true)}><ShoppingCart/><b>{count}</b></button></div><nav className={menu?"open":""}>{["Pharmacy","Latest","Petcare","Consult","Adult","Health","Health Plan"].map(x=><a key={x}>{x}</a>)}</nav></header>
 <main><div className="trustbar"><span>✓ Genuine medicines</span><span>✓ Licensed pharmacy</span><span>✓ Pickup + Home delivery</span><span>✓ Secure payments</span></div>
 <section className="hero"><div><div className="eyebrow">WELLCARE MEDICOSE · YOUR LOCAL PHARMACY ONLINE</div><h1>Healthcare that comes<br/>to <em>your doorstep.</em></h1><p>Choose your Wellcare store and order online for pickup or home delivery.</p><div className="heroBtns"><button className="primary" onClick={()=>setCat("")}>Shop medicines <ArrowRight size={17}/></button><button className="outline" onClick={()=>setRx(true)}><Upload size={17}/> Upload prescription</button></div></div><div className="heroVisual"><div className="floatCard"><ShieldCheck/><b>Trusted pharmacy</b><span>Quality checked</span></div><div className="medicineOrb">💊</div><div className="deliveryCard"><Truck/><div><b>Pickup or delivery</b><span>Choose at checkout</span></div></div></div></section>
 <section className="quick"><button onClick={()=>setCat("")}><span>💊</span><b>Order medicines</b><small>Search & shop</small></button><button onClick={()=>setRx(true)}><span>📄</span><b>Upload prescription</b><small>Pharmacy review</small></button><button onClick={()=>setCheckout(true)}><span>🏪</span><b>Choose store</b><small>Pickup or delivery</small></button><button onClick={()=>setCheckout(true)}><span>🔁</span><b>My cart</b><small>{count} item(s)</small></button></section>
 <section><div className="sectionHead"><div><h2>Shop by health need</h2><p>Find what you need faster.</p></div></div><div className="cats">{cats.map(([c,i])=><button className="cat" key={c} onClick={()=>setCat(c==="Medicines"?"":c)}><div className="catIcon">{i}</div><b>{c}</b></button>)}</div></section>
 <section><div className="sectionHead"><div><h2>{cat||"Popular healthcare"}</h2><p>{branch?"Available at your selected store":"Select a store to see availability."}</p></div></div><div className="products">{shown.length?shown.map(p=><article className="product" key={p.id}><button className="heart"><Heart size={17}/></button><div className="productImg">{p.img}</div><small>{p.b}</small><h3>{p.n}</h3><span>{p.salt}</span>{p.rx&&<label className="rx">Rx prescription required</label>}<div className="rating"><Star size={13} fill="currentColor"/> 4.8 <span>· Genuine product</span></div><div className="buy"><div><b>₹{p.p}</b> <del>₹{p.mrp}</del></div><button disabled={p.stock===0} onClick={()=>add(p)}>{p.stock===0?"Out of stock":<><Plus size={16}/> Add</>}</button></div></article>):<div className="empty">No products available at this store.</div>}</div></section>
 <section className="rxBanner"><div><div className="iconBox"><FileText/></div><div><h2>Have a prescription?</h2><p>Upload a clear photo or PDF. Our pharmacy team will review it before dispensing.</p></div></div><button className="primary" onClick={()=>setRx(true)}>Upload prescription <Upload size={17}/></button></section>
 <section className="why"><div><ShieldCheck/><b>Genuine products</b><span>Trusted pharmacy sourcing.</span></div><div><Stethoscope/><b>Pharmacist review</b><span>Rx orders checked before dispatch.</span></div><div><Truck/><b>Pickup or delivery</b><span>Choose what suits you.</span></div><div><Clock/><b>Easy reorders</b><span>Keep regular medicines within reach.</span></div></section></main>
 <footer><div><b>Wellcare Medicose</b><p>Your neighbourhood pharmacy, now online.</p></div><div><b>Shop</b><span>Medicines</span><span>Vitamins</span><span>Personal Care</span></div><div><b>Help</b><span>Orders & tracking</span><span>Prescription help</span><span>Contact pharmacy</span></div></footer>
 {rx&&<div className="overlay" onClick={()=>setRx(false)}><div className="modal rxModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setRx(false)}><X/></button><div className="uploadIcon"><Upload/></div><h2>Upload prescription</h2><p>Upload a clear prescription image or PDF. Our pharmacy team will review it before dispensing.</p><label className="dropzone"><input type="file" accept="image/jpeg,image/png,image/webp,.pdf" hidden onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setError("Prescription must be 5 MB or smaller.");setRxFile(null);return}setError("");setRxFile(f)}}/><FileText size={30}/><b>{rxFile?rxFile.name:"Choose prescription"}</b><span>{rxFile?(`${(rxFile.size/1024/1024).toFixed(2)} MB selected`):"JPG, PNG, WebP or PDF · up to 5 MB"}</span></label><button className="primary full" disabled={!session||!rxFile||busy} onClick={uploadPrescription}>{busy?"Uploading…":"Upload prescription"}</button>{!session&&<p className="notice">Sign in first to securely upload your prescription.</p>}{error&&<div className="authError">{error}</div>}</div></div>}
 {login&&<div className="overlay" onClick={()=>setLogin(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLogin(false)}><X/></button><div className="loginLogo">W</div><h2>{session?"Your Wellcare account":"Welcome to Wellcare"}</h2><p>{session?"You are signed in.":"Sign in to manage orders, saved addresses and more."}</p>{session?<button className="primary full" onClick={logout}><LogOut size={17}/> Sign out</button>:<><button className="google" onClick={google} disabled={busy}>Continue with Google</button><div className="or"><span>or</span></div>{!otpSent?<><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 mobile number" inputMode="tel"/><button className="primary full" onClick={send}>Send OTP</button></>:<><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="6-digit OTP" inputMode="numeric" maxLength="6"/><button className="primary full" onClick={verify}>{busy?"Verifying…":"Verify & sign in"}</button></>}</>}{error&&<div className="authError">{error}</div>}</div></div>}
 {checkout&&<div className="overlay" onClick={()=>setCheckout(false)}><div className="modal checkout" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setCheckout(false)}><X/></button><h2>Choose how you want your order</h2><label className="fieldLabel">Wellcare store</label><select value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name} · {b.city}</option>)}</select><div className="fulfil"><button className={method==="delivery"?"selected":""} onClick={()=>setMethod("delivery")}><Truck/><b>Home delivery</b><small>We deliver to your address</small></button><button className={method==="pickup"?"selected":""} onClick={()=>setMethod("pickup")}><Store/><b>Store pickup</b><small>Collect from the selected store</small></button></div>{method==="delivery"&&<><label className="fieldLabel">Delivery address</label>{session&&addresses.length?<select value={address} onChange={e=>setAddress(e.target.value)}>{addresses.map(a=><option key={a.id} value={a.id}>{a.label||"Address"} · {a.full_address}</option>)}</select>:<p className="notice">Sign in and add an address to use home delivery.</p>}</>}<label className="fieldLabel">Payment</label><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Cash on delivery / pickup</option><option value="upi">UPI (payment setup required)</option><option value="card">Card (payment setup required)</option></select><div className="checkoutTotal"><span>{count} items</span><b>₹{total.toLocaleString("en-IN")}</b></div><button className="primary full" disabled={!count||busy} onClick={order}>{busy?"Placing order…":method==="pickup"?"Place pickup order":"Place delivery order"}</button><small className="checkoutNote">Online UPI/card is not marked paid until the payment gateway verifies it.</small></div></div>}
 {message&&<div className="toast successToast" onClick={()=>setMessage("")}>{message}</div>}</>}
createRoot(document.getElementById("root")).render(window.location.pathname.startsWith("/portal")?<Portal/>:<App/>);