import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Search,ShoppingCart,UserRound,MapPin,ChevronRight,Plus,Minus,Menu,X,Heart,Package,ShieldCheck,LogOut,Upload,Clock,Truck,FileText,Star,ArrowRight,Stethoscope,Tag}from"lucide-react";import{supabase}from"./lib/supabase";import{googleLogin,sendPhoneOtp,verifyPhoneOtp,signOut,ensureProfile}from"./lib/auth";import"./styles.css";import Portal from"./portal";
const products=[{id:1,n:"Dolo 650",b:"Micro Labs",p:30,mrp:35,c:"Pain Relief",salt:"Paracetamol 650mg",rx:false,img:"💊"},{id:2,n:"Limcee Vitamin C 500mg",b:"Abbott",p:22,mrp:25,c:"Vitamins",salt:"Vitamin C",rx:false,img:"🍊"},{id:3,n:"Honitus Sugar Free 100ml",b:"Dabur",p:145,mrp:165,c:"Cough & Cold",salt:"Herbal formulation",rx:false,img:"🧴"},{id:4,n:"Cetaphil Gentle Skin Cleanser",b:"Galderma",p:399,mrp:450,c:"Skin Care",salt:"Gentle cleanser",rx:false,img:"🧼"},{id:5,n:"Pedigree Adult Dog Food",b:"Pedigree",p:210,mrp:240,c:"Pet Care",salt:"Adult nutrition",rx:false,img:"🐕"},{id:6,n:"First Aid Kit",b:"Wellcare",p:299,mrp:349,c:"First Aid",salt:"Essential first aid",rx:false,img:"🩹"},{id:7,n:"Shelcal 500",b:"Torrent",p:118,mrp:135,c:"Bone & Joint",salt:"Calcium + Vitamin D3",rx:false,img:"💊"},{id:8,n:"Azithromycin 500mg",b:"Cipla",p:92,mrp:105,c:"Anti Infective",salt:"Azithromycin",rx:true,img:"💊"}];
const cats=[["Medicines","💊"],["Pain Relief","🩹"],["Cough & Cold","🌿"],["Vitamins","🍊"],["Diabetes","🩺"],["Heart Care","❤️"],["Skin Care","🧴"],["Baby Care","🍼"],["Pet Care","🐾"],["First Aid","🩺"]];
function App(){const[cart,setCart]=useState([]),[login,setLogin]=useState(false),[menu,setMenu]=useState(false),[search,setSearch]=useState(""),[session,setSession]=useState(null),[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[otpSent,setOtpSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[cat,setCat]=useState(""),[rx,setRx]=useState(false);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session?.user)ensureProfile(data.session.user)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s?.user)ensureProfile(s.user)});return()=>data.subscription.unsubscribe()},[]);
const shown=useMemo(()=>products.filter(p=>(!cat||p.c===cat)&&p.n.toLowerCase().includes(search.toLowerCase())||(!cat&&search&&p.salt.toLowerCase().includes(search.toLowerCase()))),[search,cat]);
async function google(){setBusy(true);setError("");const{error}=await googleLogin();if(error)setError(error.message);setBusy(false)}
async function send(){setBusy(true);setError("");const normalized=phone.trim().startsWith("+")?phone.trim():"+91"+phone.replace(/\D/g,"");const{error}=await sendPhoneOtp(normalized);if(error)setError(error.message);else{setPhone(normalized);setOtpSent(true)}setBusy(false)}
async function verify(){setBusy(true);setError("");const{data,error}=await verifyPhoneOtp(phone,otp.trim());if(error)setError(error.message);else{setSession(data.session);setLogin(false);setOtpSent(false);setOtp("")}setBusy(false)}
function add(p){setCart(c=>[...c,p])}async function logout(){await signOut();setLogin(false)}
return <><header><div className="top"><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="logo"><span>W</span><b>Wellcare</b><small>MEDICOSE</small></div><div className="location"><MapPin size={18}/><div><small>Delivering to</small><strong>Aligarh, Uttar Pradesh</strong></div></div><div className="searchWrap"><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search medicines, brands, salt or health products"/></div>{search&&<div className="suggest"><b>Search results for “{search}”</b>{products.filter(p=>(p.n+" "+p.b+" "+p.salt).toLowerCase().includes(search.toLowerCase())).slice(0,5).map(p=><button key={p.id} onClick={()=>setSearch(p.n)}><span>{p.img}</span><div><b>{p.n}</b><small>{p.b} · {p.salt}</small></div><strong>₹{p.p}</strong></button>)}</div>}</div><button className="account" onClick={()=>setLogin(true)}><UserRound/><span>{session?.user?.user_metadata?.name||"Account"}</span></button><button className="cart"><ShoppingCart/><b>{cart.length}</b></button></div><nav className={menu?"open":""}>{["Pharmacy","Latest","Petcare","Consult","Adult","Health","Health Plan"].map(x=><a key={x}>{x}</a>)}</nav></header>
<main><div className="trustbar"><span>✓ Genuine medicines</span><span>✓ Licensed pharmacy</span><span>✓ Secure payments</span><span>✓ Fast local delivery</span></div>
<section className="hero"><div><div className="eyebrow">WELLCARE MEDICOSE · YOUR LOCAL PHARMACY ONLINE</div><h1>Healthcare that comes<br/>to <em>your doorstep.</em></h1><p>Medicines, wellness and everyday healthcare from a pharmacy you can trust.</p><div className="heroBtns"><button className="primary">Shop medicines <ArrowRight size={17}/></button><button className="outline" onClick={()=>setRx(true)}><Upload size={17}/> Upload prescription</button></div><small className="heroNote">Prescription medicines are reviewed by our pharmacy team before dispatch.</small></div><div className="heroVisual"><div className="floatCard"><ShieldCheck/><b>Trusted pharmacy</b><span>Quality checked</span></div><div className="medicineOrb">💊</div><div className="deliveryCard"><Truck/><div><b>Fast delivery</b><span>Across Aligarh</span></div></div></div></section>
<section className="quick"><button onClick={()=>setCat("Medicines")}><span>💊</span><b>Order medicines</b><small>Search & shop</small></button><button onClick={()=>setRx(true)}><span>📄</span><b>Upload prescription</b><small>We'll prepare your order</small></button><button><span>🩺</span><b>Talk to pharmacist</b><small>Get help with your order</small></button><button><span>🔁</span><b>Repeat your order</b><small>Buy again quickly</small></button></section>
<section><div className="sectionHead"><div><h2>Shop by health need</h2><p>Find what you need faster.</p></div><a>View all <ChevronRight size={17}/></a></div><div className="cats">{cats.map(([c,i])=><button className="cat" key={c} onClick={()=>setCat(c==="Medicines"?"":c)}><div className="catIcon">{i}</div><b>{c}</b></button>)}</div></section>
<section><div className="sectionHead"><div><h2>{cat||"Popular healthcare"}</h2><p>{cat?"Products in this category":"Everyday essentials customers love."}</p></div><a>View all <ChevronRight size={17}/></a></div><div className="products">{shown.length?shown.map(p=><article className="product" key={p.id}><button className="heart"><Heart size={17}/></button><div className="productImg">{p.img}</div><small>{p.b}</small><h3>{p.n}</h3><span>{p.salt}</span>{p.rx&&<label className="rx">Rx prescription required</label>}<div className="rating"><Star size={13} fill="currentColor"/> 4.8 <span>· Genuine product</span></div><div className="buy"><div><b>₹{p.p}</b> <del>₹{p.mrp}</del></div><button onClick={()=>add(p)}><Plus size={16}/> Add</button></div></article>):<div className="empty">No products found. Try medicine name, brand or salt.</div>}</div></section>
<section className="rxBanner"><div><div className="iconBox"><FileText/></div><div><h2>Have a prescription?</h2><p>Upload a clear photo or PDF. Our pharmacy team will review it and prepare the medicines for you.</p></div></div><button className="primary" onClick={()=>setRx(true)}>Upload prescription <Upload size={17}/></button></section>
<section className="why"><div><ShieldCheck/><b>Genuine products</b><span>Sourced through trusted channels.</span></div><div><Stethoscope/><b>Pharmacist review</b><span>Prescription orders are checked before dispatch.</span></div><div><Truck/><b>Reliable delivery</b><span>Order updates from confirmation to doorstep.</span></div><div><Clock/><b>Easy reorders</b><span>Keep regular medicines within reach.</span></div></section></main>
<footer><div><b>Wellcare Medicose</b><p>Your neighbourhood pharmacy, now online.</p></div><div><b>Shop</b><span>Medicines</span><span>Vitamins</span><span>Personal Care</span></div><div><b>Help</b><span>Orders & tracking</span><span>Prescription help</span><span>Contact pharmacy</span></div><div><b>Policies</b><span>Privacy</span><span>Terms</span><span>Prescription policy</span></div></footer>
{rx&&<div className="overlay" onClick={()=>setRx(false)}><div className="modal rxModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setRx(false)}><X/></button><div className="uploadIcon"><Upload/></div><h2>Upload prescription</h2><p>Upload a clear prescription image or PDF. Our pharmacy team will review it before dispensing prescription medicines.</p><label className="dropzone"><input type="file" accept="image/*,.pdf" hidden/><FileText size={30}/><b>Choose prescription</b><span>JPG, PNG or PDF · up to 5 MB</span></label><small className="privacy">🔒 Your prescription is stored privately and accessed only for order processing.</small></div></div>}
{login&&<div className="overlay" onClick={()=>setLogin(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLogin(false)}><X/></button><div className="loginLogo">W</div><h2>{session?"Your Wellcare account":"Welcome to Wellcare"}</h2><p>{session?"You are signed in.":"Sign in to manage orders, saved addresses and more."}</p>{session?<button className="primary full" onClick={logout}><LogOut size={17}/> Sign out</button>:<><button className="google" onClick={google} disabled={busy}>Continue with Google</button><div className="or"><span>or</span></div>{!otpSent?<><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 mobile number" inputMode="tel"/><button className="primary full" onClick={send} disabled={busy||phone.length<10}>{busy?"Sending…":"Send OTP"}</button></>:<><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="6-digit OTP" inputMode="numeric" maxLength="6"/><button className="primary full" onClick={verify} disabled={busy||otp.length<6}>{busy?"Verifying…":"Verify & sign in"}</button><button className="secondary full" onClick={()=>setOtpSent(false)}>Change number</button></>}</>}{error&&<div className="authError">{error}</div>}<small>By continuing, you agree to our Terms and Privacy Policy.</small></>}</div></div>}</>}
createRoot(document.getElementById("root")).render(window.location.pathname.startsWith("/portal")?<Portal/>:<App/>);