import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{supabase}from"./lib/supabase";
import{googleLogin,signOut}from"./lib/auth";
import{Store,Users,ShoppingBag,IndianRupee,Plus,LogOut,ShieldCheck,MapPin,Truck,PackageCheck,RefreshCw}from"lucide-react";
import"./portal.css";

export default function Portal(){
 const[session,setSession]=useState(null),[role,setRole]=useState(null),[branches,setBranches]=useState([]),[selected,setSelected]=useState(""),[staff,setStaff]=useState([]),[orders,setOrders]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(""),[showBranch,setShowBranch]=useState(false),[showInvite,setShowInvite]=useState(false);
 const[branch,setBranch]=useState({name:"",code:"",phone:"",address:"",city:"Aligarh",state:"Uttar Pradesh",pincode:""});
 const[email,setEmail]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>load(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>load(s));return()=>data.subscription.unsubscribe()},[]);
 async function load(s){setSession(s);if(!s){setBusy(false);return}const{data:r}=await supabase.from("user_roles").select("role").eq("user_id",s.user.id).maybeSingle();setRole(r?.role||"customer");if(r?.role==="admin"){await loadAdmin()}else if(r?.role==="staff"){await loadStaff(s.user.id)}setBusy(false)}
 async function loadAdmin(){const{data}=await supabase.from("branch_dashboard_summary").select("*").order("name");setBranches(data||[]);const{data:o}=await supabase.from("orders").select("id,branch_id,total,status,delivery_status,payment_status,fulfillment_method,created_at").order("created_at",{ascending:false}).limit(30);setOrders(o||[])}
 async function loadStaff(uid){const{data:m}=await supabase.from("staff_members").select("branch_id,role,active,branches:branch_id(id,name,code,city,state)").eq("user_id",uid).maybeSingle();if(m?.branch_id){setSelected(m.branch_id);const{data:b}=await supabase.from("branches").select("*").eq("id",m.branch_id).maybeSingle();setBranches(b?[b]:[]);const{data:o}=await supabase.from("orders").select("id,total,status,delivery_status,payment_status,fulfillment_method,created_at").eq("branch_id",m.branch_id).order("created_at",{ascending:false}).limit(50);setOrders(o||[])}}
 async function createBranch(e){e.preventDefault();setError("");const{error}=await supabase.from("branches").insert(branch);if(error)setError(error.message);else{setShowBranch(false);setBranch({name:"",code:"",phone:"",address:"",city:"Aligarh",state:"Uttar Pradesh",pincode:""});loadAdmin()}}
 async function invite(e){e.preventDefault();setError("");if(!selected)return setError("Select a branch first.");const{error}=await supabase.from("staff_invites").insert({email:email.trim().toLowerCase(),branch_id:selected,invited_role:"staff",invited_by:session.user.id});if(error)setError(error.message);else{setEmail("");setShowInvite(false)}}
 if(busy)return <div className="portalLoading">Loading pharmacy portal…</div>;
 if(!session)return <div className="portalLogin"><div className="portalBrand"><span>W</span><b>Wellcare</b><small>STAFF & ADMIN PORTAL</small></div><h1>Pharmacy operations, one place.</h1><p>Staff sign in with their invited Google account. Admins can manage every branch.</p><button className="googleBtn" onClick={googleLogin}>Continue with Google</button><small>Only authorised staff accounts can access branch operations.</small></div>;
 if(!["admin","staff"].includes(role))return <div className="portalLogin"><ShieldCheck size={40}/><h2>Staff access required</h2><p>This Google account is not assigned to a Wellcare branch.</p><button onClick={signOut}>Sign out</button></div>;
 const isAdmin=role==="admin";const active=branches.find(b=>b.id===selected)||branches[0];const open=orders.filter(o=>["placed","confirmed","packed","out_for_delivery"].includes(o.status)).length;const sales=orders.reduce((a,o)=>a+(Number(o.total)||0),0);
 return <div className="portal"><header className="portalTop"><div className="portalLogo"><span>W</span><div><b>Wellcare Medicose</b><small>{isAdmin?"ADMIN CONTROL CENTER":"STAFF OPERATIONS"}</small></div></div><div className="portalUser"><span>{session.user.email}</span><button onClick={signOut}><LogOut size={17}/> Sign out</button></div></header>
 <main className="portalMain"><div className="portalTitle"><div><p>PHARMACY OPERATIONS</p><h1>{isAdmin?"All stores":"Your store"} dashboard</h1><span>{isAdmin?"Monitor branches, sales, staff and fulfilment from one place.":"Manage pickup and home-delivery orders for your assigned branch."}</span></div><button className="refresh" onClick={()=>isAdmin?loadAdmin():loadStaff(session.user.id)}><RefreshCw size={17}/> Refresh</button></div>
 {isAdmin&&<section className="branchGrid">{branches.map(b=><button className={"branchCard "+(selected===b.id?"active":"")} onClick={()=>setSelected(b.id)} key={b.id}><div><Store/><b>{b.name}</b><small>{b.code} · {b.city}</small></div><strong>₹{Number(b.paid_sales||0).toLocaleString("en-IN")}</strong><span>{b.open_orders} open orders · {b.active_staff} staff</span></button>)}<button className="addBranch" onClick={()=>setShowBranch(true)}><Plus/> Add another medical store</button></section>}
 {active&&<section className="selectedStore"><div><MapPin size={18}/><div><b>{active.name}</b><span>{active.address||active.city+", "+active.state} {active.pincode||""}</span></div></div>{isAdmin&&<button onClick={()=>setShowInvite(true)}><Users size={17}/> Invite staff to this store</button>}</section>}
 <section className="stats"><div><ShoppingBag/><span>Orders</span><b>{isAdmin?active?.order_count||0:orders.length}</b></div><div><PackageCheck/><span>Open orders</span><b>{open}</b></div><div><IndianRupee/><span>Sales shown</span><b>₹{sales.toLocaleString("en-IN")}</b></div><div><Truck/><span>Fulfilment</span><b>Pickup + Delivery</b></div></section>
 <section className="orderPanel"><div className="panelHead"><div><h2>Recent orders</h2><p>Pickup and home-delivery orders are handled separately.</p></div></div><div className="orderList">{orders.length?orders.map(o=><div className="orderRow" key={o.id}><div><b>Order #{o.id}</b><small>{new Date(o.created_at).toLocaleString("en-IN")}</small></div><span className={"method "+o.fulfillment_method}>{o.fulfillment_method==="pickup"?"STORE PICKUP":"HOME DELIVERY"}</span><span className="status">{o.status.replaceAll("_"," ")}</span><strong>₹{Number(o.total||0).toLocaleString("en-IN")}</strong></div>):<div className="empty">No orders for this branch yet.</div>}</div></section>
 </main>
 {showBranch&&<div className="shade"><form className="panelModal" onSubmit={createBranch}><h2>Add medical store</h2><p>Create a branch first, then invite its staff Gmail accounts.</p>{["name","code","phone","address","city","state","pincode"].map(k=><input key={k} required={["name","code","address"].includes(k)} placeholder={k==="code"?"Branch code (e.g. WC-AL-02)":k[0].toUpperCase()+k.slice(1)} value={branch[k]} onChange={e=>setBranch({...branch,[k]:e.target.value})}/>)}<div className="modalBtns"><button type="button" onClick={()=>setShowBranch(false)}>Cancel</button><button className="save">Create store</button></div></form></div>}
 {showInvite&&<div className="shade"><form className="panelModal" onSubmit={invite}><h2>Invite staff</h2><p>The staff member should sign in using this same Gmail address. Their first successful Google sign-in will automatically attach them to this branch.</p><input type="email" required placeholder="staff@gmail.com" value={email} onChange={e=>setEmail(e.target.value)}/><div className="modalBtns"><button type="button" onClick={()=>setShowInvite(false)}>Cancel</button><button className="save">Create invitation</button></div></form></div>}
 {error&&<div className="toast">{error}</div>}
 </div>
}
createRoot(document.getElementById("root")).render(<Portal/>);